<link rel="stylesheet" href="<?php echo $home_url; ?>/web_parts_ty/contents/017/css/reset.min.css" );>
<link rel="stylesheet" href="<?php echo $home_url; ?>/web_parts_ty/contents/017/css/style.min.css" );>

  <!-------------- 
    cont_ty_017
  ---------------->
    <article class="cont_ty_017">
      <header>
        <h1>○◯◯◯の料金</h1>
        <p>※プランはサイトの状況に合わせて変更可能です。</p>
      </header>
      <!-- ===== 表＿PC ===== -->
      <section class="pc">
        <div class="outer">
          <ul>
            <li>ベーシックプラン<span>ここにベーシックプランの説明を入力。</span></li>
            <li>スタンダートプラン<span>ここにスタンダートプランの説明を入力。</span><span class="recommend">おすすめ</span></li>
            <li>アドバンスプラン<span>ここにアドバンスプランの説明を入力。</span></li>
          </ul>
        </div>
        <dl>
          <div>
            <dt>リスト01</dt>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
          </div>
          <div>
            <dt>リスト02</dt>
            <dd></dd>
            <dd></dd>
            <dd></dd>
          </div>
          <div>
            <dt>リスト03</dt>
            <dd></dd>
            <dd></dd>
            <dd></dd>
          </div>
          <div>
            <dt>リスト04</dt>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
          </div>
          <div>
            <dt>リスト05</dt>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
            <dd>説明を入力。</dd>
          </div>
          <div>
            <dt>リスト06</dt>
            <dd>500件</dd>
            <dd>1,000件</dd>
            <dd>無制限</dd>
          </div>
          <div>
            <dt>リスト07</dt>
            <dd></dd>
            <dd></dd>
            <dd></dd>
          </div>
          <div>
            <dt>リスト08</dt>
            <dd></dd>
            <dd>2,000</dd>
            <dd>10,000</dd>
          </div>
          <div>
            <dt>リスト09</dt>
            <dd></dd>
            <dd>3人</dd>
            <dd>10人</dd>
          </div>
          <div>
            <dt>リスト10</dt>
            <dd></dd>
            <dd></dd>
            <dd></dd>
          </div>
        </dl>
      </section>
      <!-- ===== 表＿SP ===== -->
      <section class="sp">
        <dl>
          <div class="inner">
            <h2>リスト01</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>説明を入力。</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト02</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd></dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト03</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd></dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト04</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>説明を入力。</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト05</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>説明を入力。</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>説明を入力。</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト06</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd>500件</dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>1,000件</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>無制限</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト07</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd></dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト08</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>2,000</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>10,000</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト09</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd>3人</dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd>10人</dd>
            </div>
          </div>
          <div class="inner">
            <h2>リスト10</h2>
            <div>
              <dt>ベーシックプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>スタンダートプラン</dt>
              <dd></dd>
            </div>
            <div>
              <dt>アドバンスプラン</dt>
              <dd></dd>
            </div>
          </div>
        </dl>
      </section>
      <div class="free_consultation"><a href="#">無料で相談する</a></div>
    </article>